# Generated by Django 4.2.11 on 2024-04-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='color',
            new_name='body_style',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='no_of_owner',
            new_name='no_of_owners',
        ),
        migrations.RemoveField(
            model_name='car',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='car',
            name='if_feature',
            field=models.BooleanField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='car_photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='miles',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='passengers',
            field=models.IntegerField(),
        ),
    ]
